### Create new User
### Must contain json unique fields - name, surname, email
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Test 2",
  "username": "Aleksei Test 2",
  "email": "aleksei2@gmail.com"
}

### Get User by Id
### Must contain GET params like ID
GET http://localhost:3000/api/users/67a4a5f2bc25a85b260e7381
Content-Type: application/json

### Get all users
### Must contain GET params like ID
GET http://localhost:3000/api/users
Content-Type: application/json

### Get User by Email
### Must contain json email field
POST http://localhost:3000/api/users/email
Content-Type: application/json

{
  "email": "aleksei@gmail.com"
}

### Update user
### Must contain json params
PUT http://localhost:3000/api/users/67a4a5f2bc25a85b260e7381
Content-Type: application/json

{
  "name": "Test 2",
  "username": "Ivan Test 2",
  "email": "aleksei3@gmail.com"
}

### Create new Account
### Must contain json unique fields - name, surname, email
POST http://localhost:3000/api/account
Content-Type: application/json

{
  "email": "aleksei2@gmail.com"
}


### OAuth
### Must contain json unique fields - name, surname, email
POST http://localhost:3000/api/auth/signin-with-oauth
Content-Type: application/json

{
  "provider": "google",
  "providerAccountId": "12121",
  "user": {
    "name": "Aleksei",
    "username": "Og",
    "email": "aleksei@gmail.com"
  }
}



### Create AI response for the question
POST http://localhost:3000/api/ai/answers
Content-Type: application/json

{
"question": "What is the difference between SQL and NoSQL databases",
"content": "Sql database are relational, structured, and use tables with predefined schemas.Example include MySQL and PostgreSQL. NoSQL databases, like MongoDb and Firebase , are flexible schema-less, and better suited for handling unstructured data and high scalability"
}